# Configuration for netlify

[build]
  # The root of the gatsby package is at the top level
  base = "/"
  command = "gatsby build"
  publish = "public/"

# Redirect internal domain to public domain
[[redirects]]
  from = "https://hungry-hopper-76f2b6.netlify.com/*"
  to = "https://chris.bentzel.net:splat"